#!/usr/bin/env python

#######################################################################
# File: $Id$
# $Author$
# $Source$
# $Revision$
# $Date$
#######################################################################

#############################################################################
# qegro project
#
# Author:
#         Luis Cabrera Sauco <lcabrera at gulic org>
#         Alberto Morales Diaz <amd77 at gulic org>
#
#         Copyleft  (C)2005-2005
#
# This file is part of qegro project.  
# This file program may be used, distributed and modified without limitation.
#
#############################################################################


