<?php
// $Id: $

// Private constants.
define('LDAPPROV_DEFAULT_FIRST_NAME', 'Anónimo');
define('LDAPPROV_DEFAULT_LAST_NAME', 'Anónimo');

/**
 * Implements hook_form_alter()
 */
function ldapprov_hack_form_alter($form_id, &$form) {
  switch($form_id) {
    case 'ldapprov_register':
      if (!module_exists('profile') ||
           variable_get('ldapprov_profile_first', '') == '' ||
           variable_get('ldapprov_profile_last', '') == '') {
        
        if (empty($form['account']['first_name']['#default_value'])) {
          $form['account']['first_name']['#default_value'] = LDAPPROV_DEFAULT_FIRST_NAME;
        }

        if (empty($form['account']['last_name']['#default_value'])) {
          $form['account']['last_name']['#default_value'] = LDAPPROV_DEFAULT_LAST_NAME;
        }
      }
      
      if (module_exists('profile') &&
          variable_get('ldapprov_profile', FALSE)) {
        $first = _ldapprov_hack_profile_get_field(variable_get('ldapprov_profile_first', ''));
        $last = _ldapprov_hack_profile_get_field(variable_get('ldapprov_profile_last', ''));
        
        if (empty($form[$first->category][$first->name]['#default_value'])) {
          $form[$first->category][$first->name]['#default_value'] = LDAPPROV_DEFAULT_FIRST_NAME;
        }
        
        if (empty($form[$last->category][$last->name]['#default_value'])) {
          $form[$last->category][$last->name]['#default_value'] = LDAPPROV_DEFAULT_LAST_NAME;
        }
      }
      
      break;
  }
}

function _ldapprov_hack_profile_get_field($name) {
  return db_fetch_object(db_query("SELECT * FROM {profile_fields} WHERE name = '%s'", $name));
}

?>
