<?php

function webchat2_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Muestra el webchat2.');
  }
}

function webchat2_desarrollo($original = 0) {
	global $user;
	if ($user->uid == 0) {
		if (isset($_COOKIE['chatname'])) {
			$name = $_COOKIE['chatname'];
		} else {
			$name = 'Anon'.rand(1,9999);
			setcookie("chatname", $name, time()+3600); // 1hour
		}
	} else {
		$name = $user->name;
		setcookie("chatname", "", time()-3600); // delete
	}

	$string =  '<script src="/mis_modulos/webchat2/webchat2.js" language="JavaScript" type="text/javascript"></script>';
	$string .= '<div align="center" style="background : #cccccc; font : italic 9pt helvetica; padding : 2px; margin : 1px ; outline : #6299CD solid 3px; border : #DEDEDE solid 2px; color : blue; text-align : center;text-align:center;">';
	//$string .= ' <div style="width: 200px; background : #efefef; text-align: left; margin: 4px; color: black;border : #DEDEDE solid 1px;outline : #6299CD solid 1px;padding:1px"><p><strong>¡¡Justo ahora!!</strong>, charla sobre el sistema de control de versiones de software <strong>Darcs</strong>... si llegas tarde, tienes un log en <a href="http://jabber.gulic.org/log.php?ymd=20060505#19:19:43">aqui</a>. </p></div>';
	$string .= ' <div style="width: 200px; background : #efefef; text-align: left; margin: 4px; color: black;border : #DEDEDE solid 1px;outline : #6299CD solid 1px;padding:1px"><strong>¡¡Preguntanos!!</strong><p>Si tienes dudas sobre el Software Libre, sobre Linux o sobre quienes estamos detrás de este Chat. (Para pegar texto usa nuestro <a href="http://pastebin.gulic.org/" target="_blank">pastebin</a>)</p></div>';
	$string .= ' <hr />';
	$string .= ' <div id="outputlist" style="overflow: auto; width: 200px; height: 200px; background : #efefef; text-align: left; margin: 5px; color: black;border : #DEDEDE solid 2px;outline : #6299CD solid 3px;padding:2px"></div>';
	$string .= ' <form action=" " onsubmit="return false;" name="chatForm" id="chatForm">';
	$string .= '  <input type="hidden" id="name" name="name" value="'.$name.'" />';
	$string .= '  <input onblur="checkStatus(\'\');" onfocus="checkStatus(\'active\');" type="text" name="chatbarText" size="20" maxlength="500" id="chatbarText" class="user" />';
	$string .= '  <span>Nick: <strong>'.$name.'</strong> <input type="submit" name="submit" value="Enviar" id="submit" class="submit" onclick="sendComment();" /></span>';
	$string .= ' </form>';
	$string .= '</div>';
	return $string;
}

function webchat2_block($op = 'list', $delta = 0) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Bloque para webchat2');
      return $blocks;
    case 'configure':
      return array();
    default:
      $block['subject'] = t('Ayuda OnLine de Gulic');
      $block['content'] = webchat2_desarrollo();
      return $block;
  }
}

?>
