<?php
// $Id$

// Private constants. 
define('UPDATE_BLOGFEED_FEEDURL', 'profile_blogfeed');
define('UPDATE_BLOGFEED_HOMEPAGE', 'profile_homepage');
define('UPDATE_BLOGFEED_REFRESH', 3600);
define('UPDATE_BLOGFEED_CHECKED', 1200000000);

/**
 * Implementation of hook_help().
 */
function update_blogfeed_help($section) {
  $output = '';

  switch ($section) {
    case 'admin/modules#update_blogfeed':
      $output = 'update_blogfeed';
      break;
    case 'admin/help#update_blogfeed':
      $output = t("<p>The Update Personal Blog Feed provides a mechanism to
                   add the user's personal blogs to the aggregator as feeds.
                   The module also can update the feed when an user change
                   the URL in its profile.</p>");
      break;
  }
  return $output;
}

/**
 * Implementation of hook_user().
 */
function update_blogfeed_user($type, &$edit, &$user, $category = NULL) {
  switch ($type) {
    case 'insert':
    case 'update':
      if (!empty($edit[UPDATE_BLOGFEED_FEEDURL])){
        db_query("DELETE FROM {aggregator_feed} WHERE title = '%s'", $user->name);
        db_query("INSERT INTO {aggregator_feed} (title, url, link, refresh, checked) " .
	  "VALUES ('%s', '%s', '%s', %d, %d)", $user->name,
	  $edit[UPDATE_BLOGFEED_FEEDURL], $edit[UPDATE_BLOGFEED_HOMEPAGE],
	  UPDATE_BLOGFEED_REFRESH, UPDATE_BLOGFEED_CHECKED);
      }
      else
        db_query("DELETE FROM {aggregator_feed} WHERE title = '%s'", $user->name);
  }
}

/**
 * Generate HTML for the onthisdate block
 * @param op the operation from the URL
 * @param delta offset
 * @returns block HTML 
 */
function update_blogfeed_block($op='list', $delta=0) {
  // listing of blocks, such as on the admin/block page
  if ($op == "list") {
     $block[0]["info"] = t('Planet Subscriptors');
     return $block;
  }
  else if ($op == 'view') {
    $block_content = t('This page shows all messages related with GULiC and post by members:');
    $block_content .= "<p><ul>";
    // get the feeds
    $queryResult =  db_query('SELECT link, title, url FROM {aggregator_feed} ORDER BY title');
    while ($feed = db_fetch_object($queryResult)) {
        $block_content .= '<li>' . l($feed->title, $feed->link) . ' (' . l('feed', $feed->url) . ')</li>';
    }
    $block_content .= "</ul></p>";
    $block_content .= "<a href='/aggregator/rss'><img src='/misc/xml.png'></a>";
    // set up the block
    $block['subject'] = t('Subscriptors');
    $block['content'] = $block_content;
    return $block;
  }
}

?>
